# File paths
data:
  raw_dir: data/raw/
  processed_dir: data/processed/
  dataset_file: data/processed/registered_cars_dataset.csv

models:
  model_save_dir: models/ # Top-level models directory
  streamlit_model: xgboost_hp_model.pkl
  # Add specific model names if needed, e.g.:
  # linear_model_name: car_price_model.pkl
  # xgboost_model_name: car_price_xgboost_tuned_model.pkl

# Model parameters (example)
training_params:
  test_size: 0.2
  random_state: 42